# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c869fb7a04085de4e9c99c112354669c8161d16e5de57752991746275776d542405e95c7bc2f838fe3aca2c181f78266ef51bdf5c478d8ab2b07e294c220518c

test:
  secret_key_base: 3d4ee1cb5cf3f3f50c9944c9bbe7b0e0931e0263e2df7cf93ea54125fb0ef2d66042c1fae31e0ba58b97ad94564306f969b6aa28ccbd0a21648cc0f9250741e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
